[Service]
ExecStartPre=/usr/bin/install -d -o iterlife-reunion -g iterlife-reunion -m 2775 /apps/logs/webhook
ExecStartPre=/usr/bin/touch /apps/logs/webhook/iterlife-deploy-webhook.log
ExecStartPre=/usr/bin/chown iterlife-reunion:iterlife-reunion /apps/logs/webhook/iterlife-deploy-webhook.log
ExecStartPre=/usr/bin/chmod 0664 /apps/logs/webhook/iterlife-deploy-webhook.log
